services:
  taskview:
    build:
      context: .
      dockerfile: Dockerfile
    image: taskview:latest
    container_name: taskview-app
    restart: unless-stopped
    ports:
      - "3000:80"  # 映射到本地 3000 端口
    environment:
      - JWT_SECRET=${JWT_SECRET:-taskview-jwt-secret-key-please-change-in-production}
      - RUST_LOG=${RUST_LOG:-info}
      - TZ=Asia/Shanghai
    volumes:
      - taskview-data:/app/data  # 持久化数据库文件
      - taskview-logs:/var/log/nginx  # 持久化日志
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.taskview.description=TaskView - 任务看板管理系统"
      - "com.taskview.version=1.0"

volumes:
  taskview-data:
    name: taskview-data
    driver: local
  taskview-logs:
    name: taskview-logs
    driver: local

networks:
  default:
    name: taskview-network