version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: task-view-backend
    ports:
      - "20000:20000"
    environment:
      - DATABASE_URL=sqlite:///app/data/database.db
      - RUST_LOG=info
      - PORT=20000
    volumes:
      - backend_data:/app/data
    networks:
      - task-view-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: task-view-frontend
    ports:
      - "20001:80"
    depends_on:
      - backend
    networks:
      - task-view-network
    restart: unless-stopped

volumes:
  backend_data:
    driver: local

networks:
  task-view-network:
    driver: bridge